database:
  # NOTE: By design, this setting prevents the MYSQL_DATABASE environment variable
  # from affecting test runs, so that we don't accidentally affect the
  # production database during testing. If you're not concerned about that and
  # would like to have environment variable overrides, you could instead use
  # something like:
  #
  #   database: "_env:MYSQL_DATABASE:serviette_test"
  database: serviette_test

auth-dummy-login: true
